### ISSUE TITLE
Origin doesn't launch, Windows Defender marks as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by pripboy** [p0358/Fuck_off_EA_App#10]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help

### Your issue

As title says
![imagen](https://github.com/p0358/Fuck_off_EA_App/assets/65727716/d29e28c2-00f6-4c34-b65b-1ca84dde1738)

**Comment by p0358** [comment]
The file was marked by Microsoft with that detection temporarily, I think the detection should already be removed by now after I submitted it for analysis, make sure to update your Defender's definitions (most easily I think is to check for updates in Windows Update), on VirusTotal the files aren't detected by Microsoft anymore now:
- https://www.virustotal.com/gui/file/5f0bbb15f7cff8540642c28739db0cd6b15e77e5935f4e6701351eea86d929ab/detection
- https://www.virustotal.com/gui/file/29b7cd51bed02f9efa3ac93a47f6814768d94a291178a9d70ca7aa6f512020c4/detection

If the signature update doesn't help, in the meantime you can click Actions and click Allow on device I suppose...
