### ISSUE TITLE
fifa23 can not launched

### ISSUE THREAD

**Issue by dapple2** [p0358/Fuck_off_EA_App#11]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help

### Your issue

I installed the latest version of Fuck_off_EA_App,fifa23 can not launched,when I run FIFA23,EAAntiCheat does not appear, causing FIFA23 to fail to start.

**Comment by DarthMDev** [comment]
seems like a problem with the anticheat and not the origin app

**Comment by p0358** [comment]
If you previously used the patch that replaced Origin binaries, then you'll need to reinstall Origin. But if it still doesn't work, then chances are that EA has actually updated FIFA 23 itself to prevent it from allowing being launched from Origin, in which case we wouldn't be able to do much about it...

**Comment by dapple2** [comment]
I fixed the problem,you can closed,Thanks.

**Comment by p0358** [comment]
@dapple2 though you should explain how you fixed it, in case someone else runs into the same issue in the future and finds this issue here

**Comment by dapple2** [comment]
I don't know how to solve it, FIFA23 update14, can't start, but the latest update14.1, this problem is solved
