### ISSUE TITLE
Compatibility with EA DLC Unlocker by anadius

### ISSUE THREAD

**Issue by I-i-I-iIi-I-i-I** [p0358/Fuck_off_EA_App#12]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help

### Your issue

When installing EA DLC Unlocker v2 from anadius, this patch for Origin stops working because the unlocker replaces the patch file with its custom DLL, which has the same name as this patch (version.dll). Because of this, I can only use either the DLC unlocker (which is useless without this patch anyway) or the Origin patch. Can this be fixed? Or can this be fixed without fixing the code? (like renaming the patch file to some other name)

Link to EA DLC Unlocker, if you need it: https://cs.rin.ru/forum/viewtopic.php?t=104412

**Comment by p0358** [comment]
Hmm, this is quite an unfortunate coincidence then. I chose `version.dll` because it was one of the only DLLs that's loaded by all Origin executables and DLLs, while also not being under a special protection that forces the original file from system32 to be always loaded.

As for the possibilities now, I think they are as follows:
- modifying the loader project (`./src/loader`, `./premake/loader.lua`) to proxy another DLL than `version`, whilst also making sure it's still loaded by all Origin programs, and making sure to update the proxy exports (effort)
- making a mod to the project to allow compiling the Main project as a standalone DLL with a different name, then chain-load it and call its main init function, remembering that it needs to be loaded before Origin.exe loads OriginClient.dll currently
- trying to rename EA DLC Unlocker to a different name, then trying to chain-load it, which might work just fine depending on how it's coded

I definitely don't want to rename the DLL away from `version.dll` for everyone, as that'd create a support hell for everyone trying to upgrade manually. If you were to recompile the project yourself, I think the easiest course of action would be to try renaming EA DLC Unlocker, and then modify this func: https://github.com/p0358/Fuck_off_EA_App/blob/f196423edadc9c96b367417885f3d9b1d02805c4/src/loader/main.cpp#L80-L84
to add a line like `LoadLibraryA("EA_DLC_Unlocker.dll");`, assuming that's how you rename their file...

**Comment by I-i-I-iIi-I-i-I** [comment]
Thank you so much for the quick response! I tried renaming this patch and unlocker to winmm.dll and wininet.dll, but then Origin shows errors that it cannot find entry points in other different DLLs. In that case I will now try to compile the patch according to your tip.

**Comment by I-i-I-iIi-I-i-I** [comment]
So, I recompiled your patch, added the right line of code which loads the library `versi0n.dll`, renamed the unlocker to `versi0n.dll`, and everything works! (DLCs in The Sims 4 were unlocked)

Thank you so much for your help and for this wonderful patch!

**Comment by Ryleth** [comment]
> So, I recompiled your patch, added the right line of code which loads the library `versi0n.dll`, renamed the unlocker to `versi0n.dll`, and everything works! (DLCs in The Sims 4 were unlocked)
> 
> Thank you so much for your help and for this wonderful patch!

mind sharing the dll you made? or mind showing how you altered yours?

i tried talking to anadius but he won't support origin anymore so either we alter this dll or we migrate to use his dll.

**Comment by Ryleth** [comment]
> Hmm, this is quite an unfortunate coincidence then. I chose `version.dll` because it was one of the only DLLs that's loaded by all Origin executables and DLLs, while also not being under a special protection that forces the original file from system32 to be always loaded.
> 
> As for the possibilities now, I think they are as follows:
> 
>     * modifying the loader project (`./src/loader`, `./premake/loader.lua`) to proxy another DLL than `version`, whilst also making sure it's still loaded by all Origin programs, and making sure to update the proxy exports (effort)
> 
>     * making a mod to the project to allow compiling the Main project as a standalone DLL with a different name, then chain-load it and call its main init function, remembering that it needs to be loaded before Origin.exe loads OriginClient.dll currently
> 
>     * trying to rename EA DLC Unlocker to a different name, then trying to chain-load it, which might work just fine depending on how it's coded
> 
> 
> I definitely don't want to rename the DLL away from `version.dll` for everyone, as that'd create a support hell for everyone trying to upgrade manually. If you were to recompile the project yourself, I think the easiest course of action would be to try renaming EA DLC Unlocker, and then modify this func:
> 
> https://github.com/p0358/Fuck_off_EA_App/blob/f196423edadc9c96b367417885f3d9b1d02805c4/src/loader/main.cpp#L80-L84
> 
> to add a line like `LoadLibraryA("EA_DLC_Unlocker.dll");`, assuming that's how you rename their file...

is it hard to add a function to the dll that checks if another .dll is present or not for those who have little experience coding? (load anadius.dll for example) or to make a second dll that loads it?

-is present=yes - load 'anadius.dll'
-is present=no - ignore/load original

for example, the Fuck_off_EA_App_installer.exe would have a screen asking - do you have anadius's patch installed?

check yes: check if version.dll is installed,rename it to "anadius.dll", install your .dll with a patch to load the "anadius.dll"
check no: install original version.dll without patch for another dll

**Comment by I-i-I-iIi-I-i-I** [comment]
> > So, I recompiled your patch, added the right line of code which loads the library `versi0n.dll`, renamed the unlocker to `versi0n.dll`, and everything works! (DLCs in The Sims 4 were unlocked)
> > Thank you so much for your help and for this wonderful patch!
> 
> mind sharing the dll you made? or mind showing how you altered yours?
> 
> i tried talking to anadius but he won't support origin anymore so either we alter this dll or we migrate to use his dll.

If this is still relevant, I attach the archive with the recompiled patch, you need to install the unlocker, rename version.dll in the folder with Origin to versi0n.dll, and paste my version.dll from the archive.
[version.zip](https://github.com/p0358/Fuck_off_EA_App/files/11984427/version.zip)

**Comment by Ryleth** [comment]
> > mind sharing the dll you made? or mind showing how you altered yours?
> > i tried talking to anadius but he won't support origin anymore so either we alter this dll or we migrate to use his dll.
> 
> If this is still relevant, I attach the archive with the recompiled patch, you need to install the unlocker, rename version.dll in the folder with Origin to versi0n.dll, and paste my version.dll from the archive. [version.zip](https://github.com/p0358/Fuck_off_EA_App/files/11984427/version.zip)

thank you very much; also, mind sharing how you did it? i'm trying to do it myself so whenever p0358 updates his dll i will recompile it to support anadius patch (named it anadius.dll on my end)

**Comment by I-i-I-iIi-I-i-I** [comment]
> thank you very much; also, mind sharing how you did it? i'm trying to do it myself so whenever p0358 updates his dll i will recompile it to support anadius patch (named it anadius.dll on my end)

I do not understand what your problem is, because the developer of the patch explained everything in great detail.
You need to find this function:
https://github.com/p0358/Fuck_off_EA_App/blob/f196423edadc9c96b367417885f3d9b1d02805c4/src/loader/main.cpp#L80-L84
and add a line of code to it, which will load the dll library, the developer also gave this line of code.


After adding the code line the function should look like this:
![image](https://github.com/p0358/Fuck_off_EA_App/assets/88761065/e3015fab-d7fb-41ca-9f81-3d29f8bba329)

That's it, you can recompile. The whole procedure with adding one line of code takes a couple of seconds, seriously... If you really wanted to, you could do it yourself, because it's all explained.
