### ISSUE TITLE
Doesn't works via Wine but works in Windows virtual machine

### ISSUE THREAD

**Issue by Crd5** [p0358/Fuck_off_EA_App#18]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

It perfectly works in Windows 11 ARM VM (Parallels 18) but doesn't work via Wine 7.7.0 (apple game porting toolkit 0.2 with [Whisky](https://github.com/IsaacMarovitz/Whisky)) When I take folders from VM (ProgramFiles x86, ProgramData, Appdata/local, Appdata/roaming) it doesn't work too.

P.S. Using a program or adding a versions.dll file manually doesn't help in Wine but both options work fine in Virtual Machine

<img width="1800" alt="Снимок экрана 2023-07-29 в 21 06 29" src="https://github.com/p0358/Fuck_off_EA_App/assets/62203291/61eb466e-af6c-40d5-8d51-8ca79863b52b">

<img width="1065" alt="Снимок экрана 2023-07-29 в 21 09 16" src="https://github.com/p0358/Fuck_off_EA_App/assets/62203291/66a5aa80-2e04-41eb-ad62-6e6f9353422e">

**Comment by begin-theadventure** [comment]
Did you use a DLL override?

**Comment by Crd5** [comment]
> Did you use a DLL override?

Of course. Using a program or adding a file manually doesn't help in Wine but both options work fine in Virtual Machine

**Comment by Crd5** [comment]
I found a solution. Just change version dll in winecfg to native, built-in.

<img width="500" alt="Снимок экрана 2023-07-30 в 13 14 23" src="https://github.com/p0358/Fuck_off_EA_App/assets/62203291/0ea9725d-8140-47c4-9b60-d47c233b19d8">
<img width="1065" alt="Снимок экрана 2023-07-30 в 13 15 45" src="https://github.com/p0358/Fuck_off_EA_App/assets/62203291/63fe2576-f1d8-4a92-9223-6582f5c6b2ce">
