### ISSUE TITLE
can't log in into origin

### ISSUE THREAD

**Issue by MajoMcBalls** [p0358/Fuck_off_EA_App#20]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

when i open origin it tells me that i need to be offline cuz it can't update itself i don't know what to do.

**Comment by barci335** [comment]
https://github.com/p0358/Fuck_off_EA_App/issues/19#issuecomment-1658970308

**Comment by p0358** [comment]
Should now be fixed in v3, feel free to reopen if not
