### ISSUE TITLE
Fifa 22 no activation

### ISSUE THREAD

**Issue by kolanski** [p0358/Fuck_off_EA_App#23]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

Fifa 22 say the origin in offline mode, so it cant activate. Any workaround for this?

**Comment by WarlockZone** [comment]
Same with Battlefield 3.

**Comment by WarlockZone** [comment]
> Same with Battlefield 3. ![Bug](https://user-images.githubusercontent.com/56973766/284347688-357e8fa8-da78-4af6-8dec-e49cb83664b8.png) ![Bug2](https://user-images.githubusercontent.com/56973766/284347676-d93e5bfa-6359-4c29-9ba0-a251c973a5a5.png)

Sry for a trouble. It's not problem with this project. It's buggy EA activation system at all. Even with EA App, same message appers. I delete file C:\ProgramData\Electronic Arts\EA Services\License\DGR01609244.dlf file and activation succeded.
