### ISSUE TITLE
i just wanna uninstall it 

### ISSUE THREAD

**Issue by Tf2NotWORK** [p0358/Fuck_off_EA_App#24]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

I cannot find a way to Uninstall this

**Comment by p0358** [comment]
You can just remove `version.dll` from Origin installation dir (`C:\Program Files (x86)\Origin`).

There's nothing else the installer drops apart from this and optionally the registry key to pretend EA App is installed:
https://github.com/p0358/Fuck_off_EA_App/blob/0facc8a77824ef98a1dbecdc0b693079a74f9a37/setup.iss#L42-L46
