### ISSUE TITLE
EA is dumb - the registry key location for "InstallSuccessful" is incorrect for the .exe installer of the Fuck off EA App

### ISSUE THREAD

**Issue by Tiagoquix** [p0358/Fuck_off_EA_App#29]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

Steam's installscripts (installscript.vdf inside game folders) actually check

`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\WOW6432Node\Electronic Arts\EA Desktop\InstallSuccessful`

instead of

`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Electronic Arts\EA Desktop\InstallSuccessful`

Notice that they create a "WOW6432Node" inside the original "WOW6432Node". This is true for basically every EA game.

**Comment by p0358** [comment]
Hm, odd cause I have both Origin and EA App and don't have that key, unless it's some bug from older versions. I wouldn't add that key currently then, as it's not proven to solve any particular issue, and I don't want to run into the risk of confusing people by adding extra keys (as they may run into a situation where they need to change some key, they'll find the wrong one, and then be wondering why there was no effect of the change etc)
