### ISSUE TITLE
Windows XP/Vista support on modern origin

### ISSUE THREAD

**Issue by Batuhan445** [p0358/Fuck_off_EA_App#32]
### Checklist

- [x] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [x] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [x] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [x] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

Will there any work on this issue?

**Comment by p0358** [comment]
It's not possible to get newest Origin to work on these systems, no. The underlying WebKit wouldn't run on these and it wouldn't be easy to try to work around that.

It'd be more feasible to get older Origin working with the APIs again, it's mostly the login that's broken. But I also have currently zero time or incentive to work on that, especially that Origin will likely eventually be sunset after the Mac version of EA App releases. But I have a bunch of notes on gists if anyone wants to work on that for whatever reason...
