### ISSUE TITLE
Does this work with EA app?

### ISSUE THREAD

**Issue by whatcorey** [p0358/Fuck_off_EA_App#36]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

I already have EA installed, me, as well as several other people are wondering if we can use this when we have the EA app installed

**Comment by p0358** [comment]
Yeah you can, there's explicit code in Origin to handle that

**Comment by whatcorey** [comment]
> Yeah you can, there's explicit code in Origin to handle that

Can i still play online with this and get my rewards and stuff? I'm hoping i can use this when im online and then have it for convenance when i lose internet and still have the ability to play offline

**Comment by p0358** [comment]
Yeah, people used this to be able to unlock achievements

**Comment by whatcorey** [comment]
> Yeah, people used this to be able to unlock achievements

Nice!, so i  can have this installed, and then when i want to play online, i can play online normally, and when i lose internet, i can still play without internet, all without moving anything around after installation, correct?
