### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by MustafaSasaa123** [p0358/Fuck_off_EA_App#4]
its working online but offline there is an issue.
When i go offline and click on the game.exe it wont open the game but when i open it from origin it works perfectly.
please fix

**Comment by MustafaSasaa123** [comment]
![Screenshot 2023-0sssssss6-24 184513](https://github.com/p0358/Fuck_off_EA_App/assets/137357486/b7e26914-913e-403c-b6f7-d4d2fd022b5d)
when it is offline like this and click the game.exe it wont launch but when origin offline like the 2nd screenshot it works.
![Screenshot 2023-06dddddd-24 184625](https://github.com/p0358/Fuck_off_EA_App/assets/137357486/f837338e-b5f8-4812-a7e3-e7dd61381d77)


plz fix

**Comment by p0358** [comment]
It might be Origin's own wonkiness, the offline mode basically relies on the web cache working, I think. Not sure why launching from exe would be broken, was it working before though (in offline mode)?

**Comment by MustafaSasaa123** [comment]
yes it was working before all the time even when you add the xml lines in C:\ProgramData\Origin it was working probably but in this patch it is not working from exe

**Comment by MustafaSasaa123** [comment]
> It might be Origin's own wonkiness, the offline mode basically relies on the web cache working, I think. Not sure why launching from exe would be broken, was it working before though (in offline mode)?

do yo have a fix for this in Fuck_off_EA_App patch?we need the name to start from exe like before in offline mode

**Comment by p0358** [comment]
Yeah, I'm working on it and will have a fix soon, since I managed to reproduce it

**Comment by MustafaSasaa123** [comment]
thank you. 
you are the best

**Comment by p0358** [comment]
check if it works in this version: https://github.com/p0358/Fuck_off_EA_App/suites/13839186300/artifacts/768470682

if yes, then I'll release a v2 update with this soon

**Comment by MustafaSasaa123** [comment]
> 
Big thanks 
exe works and launches the game via origin online and offline,
Thank you 

You are the bessst
