### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Twig6943** [p0358/Fuck_off_EA_App#46]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

Its been 6 months since the last commit 💀

**Comment by p0358** [comment]
yeah, it works (besides searching for people not working anymore, but cba to update readme)

> Its been 6 months since the last commit 💀

and?

**Comment by Twig6943** [comment]
I'm Linux Mint 21.3 and it seems to be not working.

**Comment by p0358** [comment]
Did you set the DLL override on version.dll? I just restarted my Origin on Windows and it loaded up, so I can tell 100% that it should work

**Comment by Twig6943** [comment]
I think so Im using proton experimental
![image](https://github.com/p0358/Fuck_off_EA_App/assets/119701717/20d81ad9-0604-4abf-b8d4-4c7b32a84212)
![image](https://github.com/p0358/Fuck_off_EA_App/assets/119701717/bcb4902a-79e2-4d90-b98e-78c45f8eff2c)
![image](https://github.com/p0358/Fuck_off_EA_App/assets/119701717/0cbc89f5-dc73-469a-8f7b-7f4d1afbfd04)

**Comment by p0358** [comment]
try `WINEDLLOVERRIDES="version=n,b" %command%`

**Comment by Twig6943** [comment]
![image](https://github.com/p0358/Fuck_off_EA_App/assets/119701717/92c0744a-070b-405f-b1e2-29809a6c9761)
OMG IT WORKED!!!!!!
Could you please mention this in readme.md? (the %command% part is missing in the readme.md)

**Comment by liquidovski** [comment]
lol

**Comment by p0358** [comment]
I added it now. Interestingly, it seems also EA recently actually FIXED searching for people, it didn't work for a few months, quite interesting.
