### ISSUE TITLE
VIRUS.. FUCK YOU

### ISSUE THREAD

**Issue by MetalKidRyzenX3D** [p0358/Fuck_off_EA_App#51]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

Chrom.Defender immediatly deleted DLL and EXE installer .. FUCK YOU MALWARE

**Comment by Xioverze** [comment]
did you.. run the dll and exe through virustotal or nah?

**Comment by Xioverze** [comment]
yeah you're tweaking, heres the virustotal link https://www.virustotal.com/gui/file/8845988dfc7ccd1ccf80d6ccb211e2aba2ce7bce75f252b73bf94480f1394fc5/behavior

look at behavior, tell me if you find anything malicious in what the program does except what it explicitly says it does, not even that but the source code is RIGHT THERE nigga go to code and read for yourself

**Comment by p0358** [comment]
It seems like pretty much all detections on virus total are just generic AI detections, so that's trash. Microsoft seems to have labeled it as `HackTool:Win32/Patcher`, which I mean yeah... I guess it patches another app, that's kinda the whole point. Could try re-submitting it for whitelisting but idk.

But yeah it's compiled by GitHub Actions and anyone can compile it themselves and bindiff to see that it's clean, it's all useless detections

**Comment by D3-3109** [comment]
@MetalKidRyzenX3D ,Accusing projects of being viruses without evidence and using aggressive language is unhelpful and unfair. Chrome can flag false positives sometimes. If you have real concerns, report them respectfully with details. Please keep the community constructive.
