### ISSUE TITLE
Game over ?

### ISSUE THREAD

**Issue by lastblade** [p0358/Fuck_off_EA_App#52]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

![image](https://github.com/p0358/Fuck_off_EA_App/assets/11603980/b036c060-092e-4c9f-87fd-4b19c2229247)

Won't load home screen anymore

**Comment by RiritoNinigaya** [comment]
it is because Origin is replaced by **EA App**

**Comment by p0358** [comment]
idk it just started up for me perfectly fine

**Comment by RiritoNinigaya** [comment]
oh okay

**Comment by lastblade** [comment]
> idk it just started up for me perfectly fine

Indeed. On my second pc, with another ea acc it loaded fine. Something is messed up on this pc.

**Comment by lastblade** [comment]
Ok i reinstalled and it came back to normal.
But this error screen keep coming back from time to time.
A temporary fix is closing the origin app and deleting the content of C:\Users\[username]\AppData\Local\Origin
