### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by User3254548** [p0358/Fuck_off_EA_App#58]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

I did everything properly 

either origin wants to update then i restart and i can go into origin 
then i restart again then only offline login
i restart again nothing works

this patch is WAY more unreliable than the new ea app

just archive this repo it doesn't have a use for anyone anymore

thx for wasting my time

**Comment by p0358** [comment]
I simply launch Origin and it just works, as do all the other users of this patch. As such, the problem seems to be in between the keyboard and the chair.

**Comment by p0358** [comment]
Also always works online and never asks for updates, despite me never disabling updates, though there's a way of doing that described in the FAQ if you'd be bothered to read. No reason to archive the repo if it still works perfectly fine.

**Comment by p0358** [comment]
>implying Origin is open-source

??? get a brain
