### ISSUE TITLE
need internet to login for the first time

### ISSUE THREAD

**Issue by rover414si** [p0358/Fuck_off_EA_App#7]
says i need internet connection to login for the first time but if i open wifi it presents me 3 options uptade the game, keep the game updated automaticly or continue in offline mode and if i do that i cannot log in?

**Comment by p0358** [comment]
It sounds like it wants Origin update, you should either update it, or block updates using the method from the FAQ for example

**Comment by p0358** [comment]
Should now be fixed in v3, feel free to reopen if not
